export default [
  {
    id: 1,
    postedOn: "2024-02-02",
    title: "iOS Developer",
    company: "Apple",
    type: "Full Time",
    experience: "Mid Level",
    location: "Remote",
    city: "Copenhagen",
    region: "Zetland",
    skills: ["SwiftUI", "UIKit", "Core Data"],
    job_Link: "https://www.apple.com/careers/us/",
  },
  {
    id: 2,
    postedOn: "2024-02-05",
    title: "Senior Frontend Developer",
    company: "WasteHero",
    type: "Full Time",
    experience: "Senior",
    location: "Hybrid",
    city: "Copenhagen",
    region: "Zetland",
    skills: ["JavaScripe", "React.js", "Computer Science", "GraphQL"],
    job_Link: "https://thehub.io/jobs/659bd29e56428bbc9d76171c",
  },
  {
    id: 3,
    postedOn: "2024-02-03",
    title: "Backend Developer",
    company: "ønskerskyen",
    type: "Full Time",
    experience: "Mid Level",
    location: "On-site",
    city: "Copenhagen",
    region: "Zetland",
    skills: ["Nodejs", "Typescript", "Kubernetes", "NestJS"],
    job_Link:
      "https://partner.onskeskyen.dk/index.php/ledig-stilling-backend-developer/",
  },
  {
    id: 4,
    postedOn: "2024-02-014",
    title: "QA Engineer",
    company: "Planday",
    type: "Full Time",
    experience: "Junior Level",
    location: "Hybrid",
    city: "Copenhagen",
    region: "Zetland",
    skills: ["Postman", "GitHub", "SQL", "WebDriver"],
    job_Link:
      "https://jobs.lever.co/xero/409e04b7-8e51-4c37-ae53-9df15b5cb5d1?source=6",
  },
];
